//==========
// except.h
//==========

#pragma once


//=======
// Using
//=======

#include <asm.h>

#ifndef __ASSEMBLER__
#include "Platform.h"
#endif


//=======
// Types
//=======

CONST_EXPR(UINT, SYNC_EXCEPTION, 0)
CONST_EXPR(UINT, FIQ_EXCEPTION, 1)
CONST_EXPR(UINT, ERROR_EXCEPTION, 2)
CONST_EXPR(UINT, INVALID_EXCEPTION, 3)


//=======
// Frame
//=======

CONST_EXPR(UINT, EXC_INSTR_SIZE, 4)
CONST_EXPR(UINT, EXC_REG_COUNT, 32)
CONST_EXPR(UINT, EXC_REG_FRAME, 29)
CONST_EXPR(UINT, EXC_REG_RETURN, 30)
CONST_EXPR(UINT, EXC_REG_STACK, 31)

STRUCT_BEGIN
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X0)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X1)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X2)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X3)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X4)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X5)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X6)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X7)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X8)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X9)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X10)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X11)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X12)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X13)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X14)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X15)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X16)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X17)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X18)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X19)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X20)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X21)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X22)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X23)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X24)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X25)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X26)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X27)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X28)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X29)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X30)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, SP)
STRUCT_END(EXC_FRAME)


//========
// Common
//========

#ifndef __ASSEMBLER__

extern "C"
{
VOID exc_restore_context(EXC_FRAME* Context);
VOID exc_resume(EXC_FRAME* Context, SIZE_T Resume, VOID* Argument);
VOID exc_save_context(EXC_FRAME* Context);
}

#endif
