//=======
// irq.h
//=======

#pragma once


//=======
// Using
//=======

#include <asm.h>


//=======
// Stack
//=======

STRUCT_BEGIN
STRUCT_FIELD(SIZE_T, 8, IRQ_STACK_, SP)
STRUCT_END(IRQ_STACK)


//=======
// Frame
//=======

STRUCT_BEGIN
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X0)
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X1)
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X2)
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X3)
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X4)
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X5)
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X6)
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X7)
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X8)
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X9)
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X10)
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X11)
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X12)
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X13)
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X14)
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X15)
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X16)
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X17)
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X18)
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X29)
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X30)
STRUCT_END(IRQ_FRAME)
