//=======
// irq.h
//=======

#pragma once


//=======
// Using
//=======

#include <asm.h>


//============
// Interrupts
//============

CONST_EXPR(UINT, IRQ_COUNT, 512);

CONST_EXPR(UINT, IRQ_TASK_SWITCH, 0);
CONST_EXPR(UINT, IRQ_SYSTIMER, 30);
CONST_EXPR(UINT, IRQ_DMA0, 112);
CONST_EXPR(UINT, IRQ_DMA1, 113);
CONST_EXPR(UINT, IRQ_DMA2, 114);
CONST_EXPR(UINT, IRQ_DMA3, 115);
CONST_EXPR(UINT, IRQ_DMA4, 116);
CONST_EXPR(UINT, IRQ_DMA5, 117);
CONST_EXPR(UINT, IRQ_DMA6, 118);
CONST_EXPR(UINT, IRQ_DMA7, 119);
CONST_EXPR(UINT, IRQ_DMA8, 120);
CONST_EXPR(UINT, IRQ_DMA9, 121);
CONST_EXPR(UINT, IRQ_DMA10, 122);
CONST_EXPR(UINT, IRQ_DMA11, 123);
CONST_EXPR(UINT, IRQ_UART10, 153);
CONST_EXPR(UINT, IRQ_PCIE_HOST_INTA, 261);
CONST_EXPR(UINT, IRQ_PCIE_HOST_MSI, 266);
CONST_EXPR(UINT, IRQ_SDIO2, 306);


//=======
// Stack
//=======

STRUCT_BEGIN
STRUCT_FIELD(SIZE_T, 8, IRQ_STACK_, SP)
STRUCT_END(IRQ_STACK)


//=======
// Frame
//=======

STRUCT_BEGIN
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X0)
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X1)
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X2)
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X3)
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X4)
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X5)
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X6)
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X7)
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X8)
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X9)
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X10)
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X11)
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X12)
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X13)
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X14)
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X15)
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X16)
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X17)
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X18)
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X29)
STRUCT_FIELD(SIZE_T, 8, IRQ_FRAME_, X30)
STRUCT_END(IRQ_FRAME)
