//==============
// Exceptions.h
//==============

#pragma once


//=======
// Using
//=======

#include "AsmHelper.h"


//===========
// Namespace
//===========

NAMESPACE(Devices)
	NAMESPACE(System)


//=================
// Exception Types
//=================

CONST_EXPR(UINT, SYNC_EXCEPTION, 0)
CONST_EXPR(UINT, FIQ_EXCEPTION, 1)
CONST_EXPR(UINT, ERROR_EXCEPTION, 2)
CONST_EXPR(UINT, INVALID_EXCEPTION, 3)


//=================
// Exception-Stack
//=================

STRUCT_BEGIN
STRUCT_FIELD(SIZE_T, 8, EXC_STACK_, DAIF)
STRUCT_FIELD(SIZE_T, 8, EXC_STACK_, SP)
STRUCT_END(EXC_STACK)


//=================
// Exception-Frame
//=================

STRUCT_BEGIN
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X0)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X1)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X2)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X3)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X4)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X5)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X6)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X7)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X8)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X9)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X10)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X11)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X12)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X13)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X14)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X15)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X16)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X17)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X18)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X29)
STRUCT_FIELD(SIZE_T, 8, EXC_FRAME_, X30)
STRUCT_END(EXC_FRAME)


//========
// Common
//========

#ifndef __ASSEMBLER__
EXC_STACK* GetExceptionStack(UINT Core);
#endif

	NAMESPACE_END
NAMESPACE_END
